name: BUILD_NGINX(ANGIE)_WITH_BORINGSSL(V3 Lite)

on:
  # you may only define up to 10 `inputs` for a `workflow_dispatch` event
  workflow_dispatch:
    inputs:
      nginx_commit_id:
        description: "指定nginx(angie)使用commit id版本"
        required: true
        default: "Angie-1.11.8"
        type: string
      ssl_commit_id:
        description: "指定BoringSSL使用commit id版本"
        required: true
        default: "0.20260616.0"
        type: string
      nginx_patch_libs:
        description: "use nginx patch libs"
        default: "native"
        type: choice
        options:
          - "native"
      build_base:
        description: "enable base build"
        default: true
        type: boolean
      build_core:
        description: "enable core build"
        default: true
        type: boolean
      release_archives:
        description: "enable release archives"
        default: true
        type: boolean

jobs:
  pre:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      default_commit_id: HEAD~0
      default_branch: ${{ steps.set_global_params.outputs.default_branch }}
      ngx_brotli_commit_id: "a71f9312c2deb28875acc7bacfdd5695a111aa53"
      brotli_lib_commit_id: "v1.2.0"
      ngx_zstd_commit_id: "057a7d339af1111d04b5a9ac5ae9b0250d17cd94"
      ngx_zstd_lee_commit_id: "09ce44eb68bccaa855206f7316fa0219a54bea3f"
      ngx_geoip2_commit_id: "445df24ef3781e488cee3dfe8a1e111997fc1dfe"
      ngx_headers_more_commit_id: "v0.40"
      njs_commit_id: "0.9.9"
      quickjs_commit_id: "04be246001599f5995fa2f2d8c91a0f198d3f34c"
      quickjs_ng_commit_id: "v0.11.0"
      ACTOR_LC: ${{ steps.set_case_params.outputs.ACTOR_LC }}
      REPOSITORY_LC: ${{ steps.set_case_params.outputs.REPOSITORY_LC }}
    steps:
      - name: set global params
        id: set_global_params
        run: |
          echo "default_branch=main" >> "$GITHUB_OUTPUT"

      - name: set lower case name
        id: set_case_params
        run: |
          echo "ACTOR_LC=${ACTOR,,}" >> "$GITHUB_OUTPUT"
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> "$GITHUB_OUTPUT"
        env:
          ACTOR: '${{ github.actor }}'
          REPOSITORY: '${{ github.repository }}'

  build-base:
    runs-on: ubuntu-latest
    needs: [pre]
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    # 同一个标签，不能多次push，会强制清空覆盖所有数据
    # strategy:
    #   matrix:
    #     os: [linux/amd64, linux/arm64]
    steps:
      #- name: Free Disk-Space
      #  run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h

      - name: (Before)Free Disk-Space
        run: df -h

      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v3  # Use @main for latest, @v3 for stable
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          #remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          #remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle"
          rm_cmd: "rmz"  # Use 'rmz' for faster deletion (default: 'rm')
          #rmz_version: "3.1.1"  # Required when rm_cmd is 'rmz'
          testing: false

      - name: (After)Free Disk-Space
        run: df -h

      - uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v10.2.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Install System Tools
        run: |
          sudo apt install -y git curl wget tree subversion

      - name: init
        run: |
          mkdir -p ${{ github.workspace }}/mainline/conf/
          cp -rf ${{ github.workspace }}/conf/* ${{ github.workspace }}/mainline/conf/
          mkdir -p ${{ github.workspace }}/mainline/patch/
          cp -rf ${{ github.workspace }}/patch/* ${{ github.workspace }}/mainline/patch/
          mkdir -p ${{ github.workspace }}/mainline/tools/
          cp -rf ${{ github.workspace }}/tools/* ${{ github.workspace }}/mainline/tools/
          tree ${{ github.workspace }}/mainline/

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 自动标签
      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@v5
      #  with:
      #    images: |
      #      ${{ secrets.DOCKERHUB_USERNAME }}/nginx
      #      ghcr.io/${{ github.repository }}

      - name: Build And Push (base)
        if: ${{ inputs.build_base }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ github.workspace }}/mainline/
          file: ${{ github.workspace }}/mainline/Base-Angie-Lite.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            NGINX_COMMIT_ID=${{ inputs.nginx_commit_id }}
            BORINGSSL_COMMIT_ID=${{ inputs.ssl_commit_id }}
            NGINX_PATCH_LIBS=${{ inputs.nginx_patch_libs }}
            NGX_BROTLI_COMMIT_ID=${{ needs.pre.outputs.ngx_brotli_commit_id }}
            BROTLI_LIB_COMMIT_ID=${{ needs.pre.outputs.brotli_lib_commit_id }}
            NGX_ZSTD_COMMIT_ID=${{ needs.pre.outputs.ngx_zstd_commit_id }}
            NGX_ZSTD_LEE_COMMIT_ID=${{ needs.pre.outputs.ngx_zstd_lee_commit_id }}
            NGX_GEOIP2_COMMIT_ID=${{ needs.pre.outputs.ngx_geoip2_commit_id }}
            NGX_HEADERS_MORE_COMMIT_ID=${{ needs.pre.outputs.ngx_headers_more_commit_id }}
            NJS_COMMIT_ID=${{ needs.pre.outputs.njs_commit_id }}
            QUICKJS_COMMIT_ID=${{ needs.pre.outputs.quickjs_commit_id }}
            QUICKJS_NG_COMMIT_ID=${{ needs.pre.outputs.quickjs_ng_commit_id }}
            BASE_IMAGE=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/base-ssl:${{ inputs.ssl_commit_id }}-boringssl-static
          push: ${{ inputs.release_archives }}
          provenance: false
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          #annotations: ${{ steps.meta.outputs.annotations }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-angie-base-boringssl-lite
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ inputs.nginx_commit_id }}-angie-base-boringssl-lite
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:angie-base-boringssl-lite-latest
            ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-angie-base-boringssl-lite
            ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:${{ inputs.nginx_commit_id }}-angie-base-boringssl-lite
            ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:angie-base-boringssl-lite-latest
          #cache-from: type=registry,ref=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:buildcache-angie-static-base
          #cache-to: type=registry,ref=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:buildcache-angie-static-base,mode=max
          # 完全禁用缓存(二选一)
          no-cache: true

      - name: Build And Push (core)
        if: ${{ inputs.build_core }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ github.workspace }}/mainline/
          file: ${{ github.workspace }}/mainline/Core.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            NGINX_COMMIT_ID=${{ inputs.nginx_commit_id }}
            BORINGSSL_COMMIT_ID=${{ inputs.ssl_commit_id }}
            BASE_IMAGE=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-angie-base-boringssl-lite
          push: ${{ inputs.release_archives }}
          provenance: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-angie-boringssl-lite
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:angie-boringssl-lite-latest
            ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-angie-boringssl-lite
            ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:angie-boringssl-lite-latest
          #cache-from: type=registry,ref=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:buildcache-angie-static-core
          #cache-to: type=registry,ref=ghcr.io/${{ needs.pre.outputs.ACTOR_LC }}/nginx:buildcache-angie-static-core,mode=max
          # 完全禁用缓存(二选一)
          no-cache: true
